codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        # basic
        target: 90%
        threshold: 0%
        if_ci_failed: error